# Generated by Django 5.0.6 on 2024-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_s', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('umur', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('shopping_interest', models.CharField(max_length=100)),
            ],
        ),
    ]
