# Generated by Django 5.0.6 on 2024-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_usersaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaya',
            name='umur',
            field=models.IntegerField(),
        ),
    ]
