# Generated by Django 5.0.6 on 2024-05-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_usersaya_umur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaya',
            name='umur',
            field=models.IntegerField(max_length=50),
        ),
    ]
